### ISSUE TITLE
[Bug]: CSS issues in NextJS when adding canonical url link in head

### ISSUE THREAD

**Issue by marnocha** [coveo/ui-kit#2725] opened 2023-02-13 18:31 UTC
### Which product are you using?

Atomic

### product version

2.0.0

### bug description

I'm trying to leverage Atomic in a Next.JS application. When I add a canonical URL to my page in the head tag, it causes issues with the Atomic CSS being applied correctly. I've reproduced this issue using your sample app. The initial page loads ok, or on a hard refresh. If you click on a navigation link then the css/styling has issues. See steps to reproduce.

Can you confirm if this is an Atomic UI CSS bug or reference a bug in Next.JS or workaround to fix? 

Thank you for review!

### Steps to reproduce

1. See modifications to index.tsx at https://github.com/marnocha/coveo-ui-kit/blob/next-test-ui-issue/packages/samples/atomic-next/pages/index.tsx
2. Integrate the changes in my repo to your index.tsx
3. Run: npm run dev
4. Open browser to the index page
5. Click on one of the nav bar links at the top of the page (similating the page having a site navigation)
6. Notice that the styling of the search box and search results now has layout issues caused by missing css
7. You can see an example of what the issue looks like at: https://github.com/marnocha/coveo-ui-kit/blob/next-test-ui-issue/packages/samples/atomic-next/public/coveo-style-issue.png

**Comment by marnocha** [comment] 2023-02-16 18:12
If it helps, I was able to workaround the UI Issue by adding this css to my css:
/* Below section is a fix for layout shifts when using React/NextJS */
atomic-layout-section[section='search'] {
    grid-area: atomic-section-search;
    grid-row-start: atomic-section-search;
    grid-column-start: atomic-section-search;
    grid-row-end: atomic-section-search;
    grid-column-end: atomic-section-search;
}
atomic-search-layout atomic-layout-section[section='search'] {
    margin: var(--atomic-layout-spacing-y) 0;
    max-width: var(--atomic-layout-max-search-box-input-width, 678px);
    width: 100%;
    justify-self: center;
}
atomic-layout-section[section='facets'] {
    grid-area: atomic-section-facets;
    grid-row-start: atomic-section-facets;
    grid-column-start: atomic-section-facets;
    grid-row-end: atomic-section-facets;
    grid-column-end: atomic-section-facets;
}
atomic-layout-section[section='main'] {
    grid-area: atomic-section-main;
    grid-row-start: atomic-section-main;
    grid-column-start: atomic-section-main;
    grid-row-end: atomic-section-main;
    grid-column-end: atomic-section-main;
}
atomic-search-layout atomic-layout-section[section='status'] {
    display: grid;
    justify-content: space-between;
    grid-template-areas:
        'atomic-breadbox atomic-breadbox'
        'atomic-query-summary atomic-sort'
        'atomic-did-you-mean atomic-did-you-mean'
        'atomic-notifications atomic-notifications';
}
atomic-search-layout atomic-layout-section[section='status'] atomic-breadbox {
    grid-area: atomic-breadbox;
    grid-row-start: atomic-breadbox;
    grid-column-start: atomic-breadbox;
    grid-row-end: atomic-breadbox;
    grid-column-end: atomic-breadbox;
}
atomic-search-layout atomic-layout-section[section='status'] atomic-query-summary {
    align-self: center;
    padding-right: 1px;
}
@media only screen 
and (max-width: 1023px) 
{ 
    atomic-search-layout atomic-layout-section[section='status'] atomic-query-summary {
        grid-area: atomic-query-summary;
    }
}
atomic-search-layout atomic-layout-section[section='status']>* {
    margin-bottom: var(--atomic-layout-spacing-y);
}
atomic-search-layout atomic-layout-section[section='status'] atomic-refine-toggle {
    grid-area: atomic-sort;
    grid-row-start: atomic-sort;
    grid-column-start: atomic-sort;
    grid-row-end: atomic-sort;
    grid-column-end: atomic-sort;
}
atomic-search-layout atomic-layout-section[section='facets'] * {
    margin-bottom: var(--atomic-layout-spacing-y);
}
atomic-search-layout atomic-layout-section[section='facets'] {
    display: none;
}
atomic-search-layout {
    width: 100%;
    height: 100%;
    display: none;
    grid-template-areas:
        '. atomic-section-search .'
        '. atomic-section-main .';
    grid-template-columns: var(--atomic-layout-spacing-x) minmax(0, 1fr) var(--atomic-layout-spacing-x);
}
atomic-search-layout atomic-layout-section[section='results'] atomic-smart-snippet {
    margin-bottom: 1.5rem;
}
atomic-search-layout atomic-layout-section[section='results'] atomic-smart-snippet-suggestions {
    margin-bottom: 1.5rem;
}

**Comment by louis-bompart** [comment] 2023-02-16 22:23
Hey @marnocha , so I did a first investigation.
The styling is dropped because something in `next/head` logic conflicts with how the CSS for the components is loaded it seems.
For this issue in particular its this rule that wreck havock when missing
```css
atomic-layout-section[section='search'] {
    grid-area: atomic-section-search;
}
```

I'll check this further next week, it's a tricky one.

**Comment by louis-bompart** [comment] 2023-02-21 22:58
Hey @marnocha, I concluded my investigation and this seems to be some NextJS and Stencil (the framework we use to create our custom components) that are butting heads.

You can see a minimal reproducible example on this repo: https://github.com/louis-bompart/animated-octo-disco

So, I will try to open issues to NextJS or Stencil and see where it goes, but as you may guess, this won't really be in our (Coveo) hands at this stage and it might takes some times before we see this fixed.

**Comment by marnocha** [comment] 2023-02-22 17:03
Hi @louis-bompart - Thank you for investigating and escalating the issue to the Stencil team!

**Comment by louis-bompart** [comment] 2023-06-07 19:32
Hey @marnocha, sorry, not yet :/ .

We started very recently investigating NextJS and how to offer first-class citizen support for it.

We will likely nix and redo our NextJS example/sample as part of this project, therefore, we won't fix the issue in the current sample.
Instead, we will verify that it doesn't occur in our next sample.

**Comment by louis-bompart** [comment] 2023-06-08 14:37
Given that: https://github.com/ionic-team/stencil/issues/4084#issuecomment-1582244131 has confirmed that this is an issue with Stencil, I'll be closing this issue as the bug has been identified on NextJS and they provided a workaround.

**Closed by louis-bompart** 2023-06-08 14:37 UTC
Labels: bug
