### ISSUE TITLE
[Bug]: Headless - disabling analytics - unwanted DELETE visit calls

### ISSUE THREAD

**Issue by marbor3** [coveo/ui-kit#2978] opened 2023-06-12 11:20 UTC
### Which product are you using?

Headless

### product version

2.18.4

### bug description

Hey!

First - I think the behaviour is intended, I would say what I need is more like `improvement` but I see only Bug report template so lets start there :)

But to the point. We're observing thousands of DELETE requests send to coveo analytics - it's happening when users do not accept analytics cookies. We're having coveo used in couple of places on page - so every page visit is then 2-3 such a requests.

I was checking sources if something could be done to avoid it, but no luck. Check steps to reproduce for details.

Thanks a lot!
Best,
Marcin

### Steps to reproduce

1. I've set in engine configuration: `analytics: false`, before it was cookie based, but just to see if maybe the issue is somewhere in my cookie checking function
2. but the requests to DELETE are still there
3. I did some debugging - there's an update of configuration as starting up the whole thing, I'm not sure why, maybe some URLs, warming up - at least that's my assumption - but it gets into this line: https://github.com/coveo/ui-kit/blob/master/packages/headless/src/features/configuration/configuration-slice.ts#L90
4. my setting is `false`, so ok, but the state is `true` so it goes into clear functionality
5. it seems like it's the default state: https://github.com/coveo/ui-kit/blob/master/packages/headless/src/features/configuration/configuration-state.ts#L133

Would it be possible to add a way to pass some initial state there? so I could then truly disable analytics and avoid this thousands of uneeded calls?

**Comment by louis-bompart** [comment] 2023-06-14 18:21
> I've set in engine configuration: analytics: false, before it was cookie based, but just to see if maybe the issue is somewhere in my cookie checking function

Hey @marbor3 , can you share a snippet of code with the full initialization of your engine?

I think you may try to set `analytics: false` instead of doing `analytics: {enabled:false}` ?

**Comment by marbor3** [comment] 2023-06-20 12:20
Ah, sorry @louis-bompart , haven't looked here in a while.

Sure thing:
```javascript
    buildSearchEngine({
        configuration: {
          analytics: {
            enabled: allowAllCookies()
          },
          organizationId: getCoveoOrganizationId() as string,
          accessToken: searchToken,
          platformUrl: getCoveoPlatformUrl(),
          search: {
            locale,
            pipeline,
            searchHub,
            preprocessSearchResponseMiddleware: (response: any) => {
              responseMiddleware?.(response);

              return response;
            }
          },
          preprocessRequest: (request, clientOrigin) => {
            if (clientOrigin === 'searchApiFetch') {
              const body = JSON.parse(request.body as string);

              body.groupBy = groupBy?.(body);

              request.body = JSON.stringify(body);
            }

            return request;
          }
        }
      }),
```

**Comment by louis-bompart** [comment] 2023-08-03 09:05
Hey @marbor3 , indeed sorry, I misread the interfaces.

After checking, I think the DELETE request are valid and are there to ensure that if the user was logged before, we wipe it down.

(let's imagine they initialy gave consent for tracking, and then remove it)

I'm curious, are you facing drawback or performance issue caused by the DELETE calls?

**Comment by marbor3** [comment] 2023-08-07 15:43
No worries!

Hmm yeah so just calling it once it's not a problem. It's just that when someone does not accept cookies these are called on every page request.
Or in our case even more - we use Coveo interfaces all over the place, it's not just search :) 
We have coveo-powered carousels with products, job offers, and events listers. 
There are pages that have like 4-5 coveo-based components - that means 5 requests, and before each 5 DELETE requests ...

Performance in this case is hard to measure for us, but we see in logs a lot of those requests so there's at least a small impact.

IMHO - since it's a headless solution, giving us building blocks to use, especially since there is an initialisation option to opt-out from analytics, we take partially into our hands the responsibility of the user's consent. - like when someone suddenly removes consent to trigger proper action.

**Comment by louis-bompart** [comment] 2023-08-07 16:17
Okay, I took good note of that, there's work behind the scene going on over analytics, and we'll try to keep your case in mind (i.e. having a true 'disabled' analytics).

We may have news early next year about that, stay tuned :)

**Comment by marbor3** [comment] 2023-08-08 05:39
Awesome! Thank you

Waiting patiently.

**Comment by louis-bompart** [comment] 2024-09-23 19:20
This should be addressed in both v2 & v3, if you use the new analyticsMode:'next', aka Event Protocol.

**Closed by louis-bompart** 2024-09-23 19:20 UTC
Labels: bug
